target-version = "py313"
line-length = 100
indent-width = 4

[lint]
select = ["ALL"]
ignore = [
  "COM812", "ISC001",  # フォーマッタ衝突回避
  "D100", "D203", "D212", "D401", "CPY001", "D104", # Docstring は緩め
  "S101", # assert許可
  "PLR2004" # magic number許可
]
preview = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

exclude = ["src/hex_commerce_service/tests/**"]

