target-version = "py313"
line-length = 140
indent-width = 4
exclude = [
  "src/tests",
  "src/scripts",
  ]

[lint]
select = ["ALL"]
ignore = [
  "COM812", "ISC001",  # フォーマッタ衝突回避
  "D100", "D203", "D212", "D401", "CPY001", "D101", "D102", "D103", "D104", "D107", "D413", "D105", "DOC402", # Docstring
  "S101", # assert許可
  "PLR2004", # magic number許可
  "SIM108", # 三項演算子を強制しない
  "EM101", "EM102",
  "TRY003",
  "TC001",
  "BLE001",
]
preview = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false


