name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup rye
        id: setup-rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          cache-prefix: 'rye-cache'

      - name: Do something if the cache was restored
        if: steps.setup-rye.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Install dependencies
        run: rye sync

      - name: Run tests
        run: rye run ci
